<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\App.Access\App.Access.csproj" />
    <ProjectReference Include="..\App.Engine\App.Engine.csproj" />
    <ProjectReference Include="..\App.Manager\App.Manager.csproj" />
  </ItemGroup>

</Project>
